import type { Metadata } from "next";
import Script from "next/script";
import Image from "next/image";
import Link from "next/link";
import SiteNav from "@/components/SiteNav";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-theme="system"
      >
        <Script id="theme-init" strategy="beforeInteractive">
          {`try{var m=window.matchMedia('(prefers-color-scheme: dark)');var c=document.cookie.match(/theme=(light|dark|system)/)?.[1]||'system';var dark=(c==='dark')||(c==='system'&&m.matches);document.documentElement.classList.toggle('dark',dark);}catch(e){}`}
        </Script>
        <header className="sticky top-3 z-50">
          <div className="container mx-auto px-6">
            <div className="backdrop-blur supports-[backdrop-filter]:bg-background/60 bg-background/80 border border-border/60 rounded-xl shadow-sm flex items-center gap-3 px-4 py-2">
              <Link href="/" className="flex items-center gap-3">
                <Image
                  src="/assets/jewel_large.png"
                  alt="HunterLab"
                  width={32}
                  height={32}
                  className="rounded"
                  priority
                />
                <span className="text-lg font-semibold">HunterLab</span>
              </Link>
              <div className="ml-auto">
                <SiteNav />
              </div>
            </div>
          </div>
        </header>
        <div className="container mx-auto px-6 py-6">{children}</div>
        <footer className="mt-16 border-t border-border/80">
          <div className="container mx-auto px-6 py-10 grid grid-cols-1 md:grid-cols-4 gap-8 text-sm">
            <div>
              <div className="flex items-center gap-2 font-semibold mb-2">
                <Image
                  src="/assets/jewel_large.png"
                  alt="HunterLab"
                  width={20}
                  height={20}
                  className="rounded"
                />
                HunterLab
              </div>
              <p className="text-muted-foreground">
                Color measurement solutions.
              </p>
            </div>
            <div>
              <div className="font-medium mb-2">Products</div>
              <ul className="space-y-1 text-muted-foreground">
                <li>
                  <Link href="/desktop" className="hover:underline">
                    Desktop
                  </Link>
                </li>
                <li>
                  <Link href="/instrument/agera" className="hover:underline">
                    Instrument
                  </Link>
                </li>
                <li>
                  <Link href="/recovery" className="hover:underline">
                    Recovery
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <div className="font-medium mb-2">Company</div>
              <ul className="space-y-1 text-muted-foreground">
                <li>
                  <a href="#" className="hover:underline">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:underline">
                    Careers
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:underline">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
            <div>
              <div className="font-medium mb-2">Resources</div>
              <ul className="space-y-1 text-muted-foreground">
                <li>
                  <a href="#" className="hover:underline">
                    Docs
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:underline">
                    Support
                  </a>
                </li>
                <li>
                  <a href="#" className="hover:underline">
                    Privacy
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className="border-t border-border/60">
            <div className="container mx-auto px-6 py-6 text-xs text-muted-foreground flex items-center justify-between">
              <span>
                © {new Date().getFullYear()} HunterLab. All rights reserved.
              </span>
              <span>v0.1.0</span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
